### ISSUE TITLE
Review the state of Asterisc and final shipping checklist

### ISSUE THREAD

**Issue by pauldowman** [ethereum-optimism/asterisc#86]
Asterisc has been developed by Sunnyside. OP Labs have understood that it's done but as we're getting ready to ship it seems that we aren't 100% clear on what loose ends might remain.

This issue will track what remains.

- [x] Review the status with Sunnyside and make sure it's ready to ship
- [x] Arrange a call with to review anything that needs further discussion
- [x] Radix trie memory implementation
- [ ] Review and fix outstanding TODOs
- [ ] Audit preparation
    - [ ] Final code review
    - [ ] Cleanups
    - [ ] Scope doc

**Comment by refcell** [comment]
Document to expand on this: https://hackmd.io/@refcell/rJfs8cr1ye

**Comment by BlocksOnAChain** [comment]
we can just close this issue, we can keep track in the hackmd or create a new issue, if we need to.
